connect to UEBUNG;

CREATE VIEW family (X,Y) AS 
WITH MOTHERANCESTRY(Ancestor, Descendant) AS
	((SELECT Mother, Child FROM MOTHERHOOD) UNION ALL
		(SELECT x.Mother, y.Descendant 
			FROM MOTHERHOOD x, MOTHERANCESTRY y 
			WHERE x.Child = y.Ancestor)),
	FATHERANCESTRY(Ancestor, Descendant) AS
	((SELECT Father, Child FROM FATHERHOOD) UNION ALL
		(SELECT x.Father, y.Descendant 
			FROM FATHERHOOD x, FATHERANCESTRY y 
			WHERE x.Child = y.Ancestor)),
	ANCESTRY(X,Y) AS
	((SELECT Ancestor, Descendant FROM MOTHERANCESTRY) UNION
	(SELECT Descendant, Ancestor FROM MOTHERANCESTRY) UNION
	(SELECT Ancestor, Descendant FROM FATHERANCESTRY) UNION 
	(SELECT Descendant, Ancestor FROM FATHERANCESTRY)),
	COMMONANCESTRY(X,Y) AS 
	(SELECT DISTINCT a.X,b.X FROM ANCESTRY a, ANCESTRY b 
		WHERE a.Y = b.Y),
	COMMONANDMARRIAGE(X,Y) AS 
		((SELECT * FROM COMMONANCESTRY) UNION
			(SELECT MAN, WOMAN FROM married) UNION
			(SELECT WOMAN, MAN FROM married)),
	RELATED(X, Y) AS
	(SELECT DISTINCT a.X, b.X 
		FROM COMMONANDMARRIAGE a, COMMONANDMARRIAGE b 
		WHERE a.Y = b.Y)
	(SELECT * FROM RELATED);

terminate;